SELECT DISTINCT ev.ID_EVENT, pe.NAMA_LENGKAP, s.NAMA_SASARAN_EVENT, se.NAMA_STATUS_EVENT, ke.NAMA_KATEGORI_EVENT, ev.NAMA_EVENT,
ev.DESKRIPSI_EVENT, ev.TGL_TERBUAT, ev.TGL_SELESAI, ev.TARGET
FROM event ev, jenis_barang jb, donasi_barang db, barang b, penggalang pe, sasaran_event s, status_event se, kategori_event ke
WHERE db.ID_BRG = b.ID_BRG AND b.ID_JENIS_BRG = jb.ID_JENIS_BRG AND jb.NAMA_JENIS_BRG = 'APD' AND db.ID_EVENT = ev.ID_EVENT
AND ev.ID_PENGGALANG = pe.ID_PENGGALANG AND s.ID_SASARAN_EVENT = ev.ID_SASARAN AND ev.ID_STATUS_EVENT = se.ID_STATUS_EVENT
AND ev.ID_KATEGORI_EVENT = ke.ID_KATEGORI_EVENT
